framework integration and image-sizing
utkwdn/utksds-theme pull request #30
Opened 2023-04-06 14:45 UTC by spworky

Integration framework into theme. (align WDS with utk.edu repos)
– pull in WDS elements as collected in style-aggregate branches (theme and framework)
– enqueue project local stylesheet
– add patterns
– fix responsive navigation

Add custom image size support. 
– add custom 'Cover Tall' size

2023-04-11 12:41 UTC, spworky commented
@pikemurdy These are the things that have changed:
– Add prettier
– Update version number
– add editorial styles
– enqueue local styles
– add Cover Tall image size as proof of concept (image size available in block editor)
– add 34 patterns and organize by WDS category, remove WordPress default patterns and categories
– make default page title match sub pages in utk.edu with orange hash
– add all previously aggregated framework css (16 component sheets, 15 region sheets, 25 styles sheets) and custom variables
– add theme.json
– update template parts used for header to fix site title spacing, responsive navigation, on canvas nav positioning, universal nav styling

2023-04-17 20:15 UTC, pikemurdy requested changes
I'm getting warnings and errors, on this.

```
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'add_block_template_part_support' not found or invalid function name in /Users/mp/Documents/--sites/utksds/wp-includes/class-wp-hook.php on line 308

Notice: Webfont src must be a non-empty string or an array of strings. in /Users/mp/Documents/--sites/utksds/wp-includes/script-loader.php on line 3371

Notice: Trying to access array offset on value of type bool in /Users/mp/Documents/--sites/utksds/wp-includes/script-loader.php on line 3445

Notice: Undefined index: font-family in /Users/mp/Documents/--sites/utksds/wp-includes/script-loader.php on line 3591

Notice: Undefined index: font-family in /Users/mp/Documents/--sites/utksds/wp-includes/script-loader.php on line 3609
```
Not sure when those appeared. The first on is due to line 344 of functions.php. Not sure what it does or why it was added.

The others appear to be web font related. Pretty sure that will be in theme.json, but I bet we can google it. Any chance we can fix these before uploading?

2023-04-17 21:59 UTC, spworky commented
I  just pushed in a fix to this branch (fix-font-error) @pikemurdy. That should resolve the errors you were seeing.

2023-04-18 12:12 UTC, pikemurdy commented
The one warning: 

```
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'add_block_template_part_support' not found or invalid function name in /Users/mp/Documents/--sites/utksds/wp-includes/class-wp-hook.php on line 308
```
Is still there. It's in `functions.php` on line 345.

2023-04-18 14:38 UTC, pikemurdy approved these changes
Good to go. We'll need to resolve all the conflicts though.

2023-04-18 17:13 UTC, merged